# Define GitHub workflow to build and test React app and open issue if tests pass
# Use the pull event to trigger the workflow
# Use ubuntu latest

name: Build and test React app
on: 
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    # First step of job is to checkout the repo
    steps: 
      - uses: actions/checkout@v3
      # Second step is to install dependencies
      - name: Install dependencies
        run: npm install
      # Third step is to build the app
      - name: Build app
        run: npm run build

      # Fourth step is to run tests
      - name: Run tests
        run: npm run test
      # Fifth step is to create issue if tests pass
      - name: Create issue
        if: ${{ success() }}
        # Use the GitHub CLI to create an issue in the repo
        run: gh issue create --title "Tests passed" --body "All tests passed, approve then deploy"
        # Use the GitHub token to authenticate
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}