name: Build and Test
on:
  pull_request:
    branches:
      - main
    
    
jobs:
  build-and-test:
    name: Build and test react app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm run test --if-present
      - name: Create Issue
        if: ${{ success() }}
        run: |
          echo "Creating issue, manual approval required"
          gh issue create --title "PR Passed Tests 2, Need Approval" --body "approve then deploy"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}